
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module test_sync_lbc_top(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	output 		    [35:0]		OutGPIO
);

wire clk = CLOCK_50;
wire n_rst = KEY[0];

assign OutGPIO[9] = n_rst;

assign OutGPIO[35:25] = 0;

//=======================================================
//  REG/WIRE declarations
//=======================================================

test_Sync_LBC tsb(
	.clk(clk),
	.n_rst(n_rst),
	
	.SCLK(OutGPIO[0]),
	.GCLK(OutGPIO[1]),
	.LAT(OutGPIO[2]),
	.SOUT(OutGPIO[3]),
	.turn_tick(OutGPIO[4]),
	.row_en(OutGPIO[8:5])

);
//=======================================================
//  Structural coding
//=======================================================



endmodule
