# TCL File Generated by Component Editor 18.1
# Tue Feb 04 16:37:49 CET 2020
# DO NOT MODIFY


# 
# Led_Band_Controller "LBC" v1.0
# LitSpin 2020.02.04.16:37:49
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Led_Band_Controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME Led_Band_Controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR LitSpin
set_module_property DISPLAY_NAME LBC
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL led_band_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file led_band_controller.sv SYSTEM_VERILOG PATH ../src/led_band_controller.sv TOP_LEVEL_FILE
add_fileset_file address_computer.sv SYSTEM_VERILOG PATH ../src/address_computer.sv
add_fileset_file led_band_FC_setter.sv SYSTEM_VERILOG PATH ../src/led_band_FC_setter.sv
add_fileset_file led_band_GS_controller.sv SYSTEM_VERILOG PATH ../src/led_band_GS_controller.sv
add_fileset_file led_band_memory.sv SYSTEM_VERILOG PATH ../src/led_band_memory.sv


# 
# parameters
# 
add_parameter NB_LED_COLUMN INTEGER 32
set_parameter_property NB_LED_COLUMN DEFAULT_VALUE 32
set_parameter_property NB_LED_COLUMN DISPLAY_NAME NB_LED_COLUMN
set_parameter_property NB_LED_COLUMN TYPE INTEGER
set_parameter_property NB_LED_COLUMN UNITS None
set_parameter_property NB_LED_COLUMN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NB_LED_COLUMN HDL_PARAMETER true
add_parameter BIT_PER_COLOR INTEGER 8
set_parameter_property BIT_PER_COLOR DEFAULT_VALUE 8
set_parameter_property BIT_PER_COLOR DISPLAY_NAME BIT_PER_COLOR
set_parameter_property BIT_PER_COLOR TYPE INTEGER
set_parameter_property BIT_PER_COLOR UNITS None
set_parameter_property BIT_PER_COLOR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BIT_PER_COLOR HDL_PARAMETER true
add_parameter NB_0_LSB INTEGER 1
set_parameter_property NB_0_LSB DEFAULT_VALUE 1
set_parameter_property NB_0_LSB DISPLAY_NAME NB_0_LSB
set_parameter_property NB_0_LSB TYPE INTEGER
set_parameter_property NB_0_LSB UNITS None
set_parameter_property NB_0_LSB ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NB_0_LSB HDL_PARAMETER true
add_parameter NB_ANGLES INTEGER 128
set_parameter_property NB_ANGLES DEFAULT_VALUE 128
set_parameter_property NB_ANGLES DISPLAY_NAME NB_ANGLES
set_parameter_property NB_ANGLES TYPE INTEGER
set_parameter_property NB_ANGLES UNITS None
set_parameter_property NB_ANGLES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NB_ANGLES HDL_PARAMETER true
add_parameter ANGLE_PCB INTEGER 0
set_parameter_property ANGLE_PCB DEFAULT_VALUE 0
set_parameter_property ANGLE_PCB DISPLAY_NAME ANGLE_PCB
set_parameter_property ANGLE_PCB TYPE INTEGER
set_parameter_property ANGLE_PCB UNITS None
set_parameter_property ANGLE_PCB ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ANGLE_PCB HDL_PARAMETER true
add_parameter W_DATA_WIDTH INTEGER 128
set_parameter_property W_DATA_WIDTH DEFAULT_VALUE 128
set_parameter_property W_DATA_WIDTH DISPLAY_NAME W_DATA_WIDTH
set_parameter_property W_DATA_WIDTH TYPE INTEGER
set_parameter_property W_DATA_WIDTH UNITS None
set_parameter_property W_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property W_DATA_WIDTH HDL_PARAMETER true
add_parameter default_FC STD_LOGIC_VECTOR 101163676500040
set_parameter_property default_FC DEFAULT_VALUE 101163676500040
set_parameter_property default_FC DISPLAY_NAME default_FC
set_parameter_property default_FC WIDTH 50
set_parameter_property default_FC TYPE STD_LOGIC_VECTOR
set_parameter_property default_FC UNITS None
set_parameter_property default_FC ALLOWED_RANGES 0:1125899906842623
set_parameter_property default_FC HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock w_clk
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave w_addr_input address Input 10
add_interface_port avalon_slave w_data writedata Input W_DATA_WIDTH
add_interface_port avalon_slave write write Input 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point driving
# 
add_interface driving conduit end
set_interface_property driving associatedClock clock
set_interface_property driving associatedReset reset_sink
set_interface_property driving ENABLED true
set_interface_property driving EXPORT_OF ""
set_interface_property driving PORT_NAME_MAP ""
set_interface_property driving CMSIS_SVD_VARIABLES ""
set_interface_property driving SVD_ADDRESS_GROUP ""

add_interface_port driving LAT lat Input 1
add_interface_port driving SCLK sclk Input 1
add_interface_port driving SOUT sout Output 1


# 
# connection point bit_choice
# 
add_interface bit_choice conduit end
set_interface_property bit_choice associatedClock clock
set_interface_property bit_choice associatedReset reset_sink
set_interface_property bit_choice ENABLED true
set_interface_property bit_choice EXPORT_OF ""
set_interface_property bit_choice PORT_NAME_MAP ""
set_interface_property bit_choice CMSIS_SVD_VARIABLES ""
set_interface_property bit_choice SVD_ADDRESS_GROUP ""

add_interface_port bit_choice angle angle Input "(non-static) - (0) + 1"
add_interface_port bit_choice bit_sel bit_sel Input "(non-static) - (0) + 1"
add_interface_port bit_choice color color Input 2
add_interface_port bit_choice row row Input "(non-static) - (0) + 1"


# 
# connection point hps
# 
add_interface hps conduit end
set_interface_property hps associatedClock ""
set_interface_property hps associatedReset ""
set_interface_property hps ENABLED true
set_interface_property hps EXPORT_OF ""
set_interface_property hps PORT_NAME_MAP ""
set_interface_property hps CMSIS_SVD_VARIABLES ""
set_interface_property hps SVD_ADDRESS_GROUP ""

add_interface_port hps hps_SOUT sout Input 1
add_interface_port hps hps_fc_clk fc_clk Input 1
add_interface_port hps hps_fc_data fc_data Input 1
add_interface_port hps hps_override override Input 1
add_interface_port hps new_frame new_frame Input 1


# 
# connection point w_clk
# 
add_interface w_clk clock end
set_interface_property w_clk clockRate 0
set_interface_property w_clk ENABLED true
set_interface_property w_clk EXPORT_OF ""
set_interface_property w_clk PORT_NAME_MAP ""
set_interface_property w_clk CMSIS_SVD_VARIABLES ""
set_interface_property w_clk SVD_ADDRESS_GROUP ""

add_interface_port w_clk w_clk clk Input 1

